import Head from 'next/head'
import {BsFillMoonStarsFill, BsFacebook, BsGithub} from 'react-icons/bs'
import {AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image'
import me from '../public/me.png'
import tri from '../public/bg-texture.png'
import web1 from '../public/bgst.png'
import web2 from '../public/craftfactory.png'
import web3 from '../public/cyd.png'
import web4 from '../public/welearn.png'
import web5 from '../public/mathgame.png'
import web6 from '../public/portfolio.png'
import {useState} from 'react'
import Nav from './Nav'
import About from './About'
import Contact from './Contact'
import {BiCheck} from 'react-icons/bi'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>DJ Luz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10 text-black bg-white md:px-20 lg:px-40 dark:bg-gray-900'>

{/*-------------- first page------------- */}
        <section className="min-h-screen" id="">
          <nav className='flex justify-between py-10 mb-12 dark:text-white'>
            <h1 className='text-xl font-burtons'><Image src={tri} />DJ Luz</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='text-2xl cursor-pointer hover:fill-teal-400' />
              </li>
              <li>
                <a className='px-5 py-2 ml-5 text-white align-middle rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black' download href='https://drive.google.com/file/d/1mdF9vylmotl7_x3MxhaEyxzahOEgaaoa/view?usp=share_link' target='_blank' >
                Download CV
                </a>
              </li>
            </ul>
          </nav>
          <div className='mb-10 me'>
            <Image src={me} />
          </div>
          <div className='text-center p-10 mt-[450px]'>
            <h2 className='py-2 text-5xl font-medium text-teal-600 md:text-6xl dark:text-teal-400'>
              Daryl Jane Luz
            </h2>
            <h3 className='py-5 text-2xl md:text-3xl dark:text-white'>Developer and designer.</h3>
            <p className='max-w-lg py-5 mx-auto leading-8 text-gray-800 text-md md:text-xl dark:text-gray-200'>
              Freelancer providing services for programming and design content needs. Join me down below and let's get coding!
            </p>
          </div>
          <div className='flex justify-center gap-16 py-2 text-5xl text-gray-600 dark:text-gray-400'>
            <a href="https://www.facebook.com/daryljaneluz" target="_blank" >
              <BsFacebook className='cursor-pointer hover:fill-teal-400'  />
            </a>
            <a href="https://www.linkedin.com/in/daryljaneluzcebu/" target="_blank" >
              <AiFillLinkedin className='cursor-pointer hover:fill-teal-400'  />
            </a>
            <a href="https://github.com/Djluz" target="_blank"  >
              <BsGithub className='cursor-pointer hover:fill-teal-400' />
            </a>
          </div>

          <Nav />
        </section>

{/*-------------- second page------------- */}
        <section className='pt-[50px] text-center mx-auto' id="about">
          <div>

            <About />

          </div>
        </section>

{/*-------------- third page------------- */}
        <section className='text-center mt-5 pt-[50px]' id="services">
          <div>
            <h3 className='py-1 text-3xl dark:text-white'>
              Services I Offer
            </h3>
            <p className='max-w-2xl py-5 mx-auto leading-8 text-gray-800 text-md dark:text-gray-200'>
              Since the beginning of my journey as a freelance designer and developer, I've done remote work for <span className='text-teal-500'>agencies</span>, consulted for <span className='text-teal-500'>startups</span> and collaborated with talented people to create digital products for both business and consumer use.
            </p>
            <p className='py-5 leading-8 text-gray-800 text-md dark:text-gray-200'>
              I offer from wide range of services, including programming and designing.
            </p>
          </div>
          <div className="gap-3 text-white md:flex lg:gap-5">
            <article className="flex-1 my-5 text-center bg-gray-700 service hover:bg-slate-100 dark:bg-gray-600">
              <div className="service__head bg-gradient-to-r from-cyan-500 to-teal-500">
                <h3>UI/UX Design</h3>
              </div>
              <ul className='service__list hover:text-black'>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>User Experience & Design</p>
                </li>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>Responsive Design </p>
                </li>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>Wireframes & Sitemaps </p>
                </li>
              </ul>
            </article>

            <article className="flex-1 my-5 text-center bg-gray-700 service hover:bg-slate-100 dark:bg-gray-600">
              <div className="service__head bg-gradient-to-r from-cyan-500 to-teal-500">
                <h3>Web Development</h3>
              </div>
              <ul className='service__list hover:text-black'>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>Laravel Development </p>
                </li>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>React JS Development </p>
                </li>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>API Integration</p>
                </li>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>Wordpress Development </p>
                </li>
              </ul>
            </article>

            <article className="flex-1 my-5 text-center bg-gray-700 service hover:bg-slate-100 dark:bg-gray-600">
              <div className="service__head bg-gradient-to-r from-cyan-500 to-teal-500">
                <h3>Content Creation</h3>
              </div>
              <ul className='service__list hover:text-black'>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>Creative Direction & Branding</p>
                </li>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>Creative Concepting </p>
                </li>
                <li>
                  <BiCheck className='service__list-icon' />
                  <p>Data Visualization & Analytics</p>
                </li>
              </ul>
            </article>
          </div>
        </section>

{/*-------------- fourth page------------- */}
        <section className='text-center pt-[50px]' id="portfolio">
          <div>
            <h3 className='py-1 text-3xl dark:text-white'>
              Portfolio
            </h3>
            <p className='max-w-2xl py-5 mx-auto leading-8 text-gray-800 text-md dark:text-gray-200'>
              This showcases the most recent projects I have done for my clients in freelancing as well as projects from Kodego Bootcamp.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='flex-1 transition ease-in-out delay-150 rounded-lg shadow-lg group basis-1/3 hover:shadow-teal-400 hover:cursor-pointer'>
              <div className='relative overflow-hidden rounded-lg'>
                <Image src={web1} className='object-cover rounded-lg' width={'100%'} height={'100%'} layout='responsive' />
                <div className='absolute flex flex-col items-center justify-center w-full h-full transition-all duration-300 rounded-lg opacity-0 bg-black/70 -bottom-10 group-hover:bottom-0 group-hover:opacity-100'>
                  <p className='px-5 py-5 text-sm text-black bg-white bg-opacity-90 md:text-xl'>Boobie Goodies & Sweet Treats is a business website I created during Kodego Bootcamp for Front-end Individual Project. This project is built without any functionalities.</p>
                  <div className='flex justify-center gap-2 mt-5 text-sm md:gap-10 md:text-lg lg:gap-3 xl:gap-10'>
                    <a href='https://bgst-website.djluz.website/' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black' >View Website</button>
                    </a>
                    <a href='https://github.com/Djluz/Boobie-Goodies---Sweet-Treats' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black'>View Github</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className='flex-1 transition ease-in-out delay-150 rounded-lg shadow-lg group basis-1/3 hover:shadow-teal-400 hover:cursor-pointer'>
              <div className='relative overflow-hidden rounded-lg'>
                <Image src={web2} className='object-cover rounded-lg' width={'100%'} height={'100%'} layout='responsive' />
                <div className='absolute flex flex-col items-center justify-center w-full h-full transition-all duration-300 rounded-lg opacity-0 bg-black/70 -bottom-10 group-hover:bottom-0 group-hover:opacity-100'>
                  <p className='px-5 py-5 text-sm text-black bg-white bg-opacity-90 md:text-xl'>Craft Factory is an E-commerce website I created with my team during Kodego Bootcamp for our Capstone Project. I did most of the front-end and back-end coding using Laravel Framework. </p>
                  <div className='flex justify-center gap-2 mt-5 text-sm md:gap-10 md:text-lg lg:gap-3 xl:gap-10'>
                    <a href='https://laravel10.craftfactory.online/' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black' >View Website</button>
                    </a>
                    <a href='https://github.com/Djluz/Craft_Factory' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black'>View Github</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className='flex-1 transition ease-in-out delay-150 rounded-lg shadow-lg group basis-1/3 hover:shadow-teal-400 hover:cursor-pointer'>
              <div className='relative overflow-hidden rounded-lg'>
                <Image src={web3} className='object-cover rounded-lg' width={'100%'} height={'100%'} layout='responsive' />
                <div className='absolute flex flex-col items-center justify-center w-full h-full transition-all duration-300 rounded-lg opacity-0 bg-black/70 -bottom-10 group-hover:bottom-0 group-hover:opacity-100'>
                  <p className='px-5 py-5 text-sm text-black bg-white bg-opacity-90 md:text-xl'>CYD is a business website for an Online Legal Service as requested by a client it is created using ReactJS and Tailwindcss.</p>
                  <div className='flex justify-center gap-2 mt-5 text-sm md:gap-10 md:text-lg lg:gap-3 xl:gap-10'>
                    <a href='https://cyd-services.djluz.website/' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black' >View Website</button>
                    </a>
                    <a href='https://github.com/Djluz/cyd-services' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black'>View Github</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className='flex-1 transition ease-in-out delay-150 rounded-lg shadow-lg group basis-1/3 hover:shadow-teal-400 hover:cursor-pointer'>
              <div className='relative overflow-hidden rounded-lg'>
                <Image src={web4} className='object-cover rounded-lg' width={'100%'} height={'100%'} layout='responsive' />
                <div className='absolute flex flex-col items-center justify-center w-full h-full transition-all duration-300 rounded-lg opacity-0 bg-black/70 -bottom-10 group-hover:bottom-0 group-hover:opacity-100'>
                  <p className='px-5 py-5 text-sm text-black bg-white bg-opacity-90 md:text-xl'>We-Learn is an E-learning website I created with my team during Kodego Bootcamp for Front-end Project 2. I did the website designing and most of the front-end coding in this project.</p>
                  <div className='flex justify-center gap-2 mt-5 text-sm md:gap-10 md:text-lg lg:gap-3 xl:gap-10'>
                    <a href='https://welearn-website.djluz.website/' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black' >View Website</button>
                    </a>
                    <a href='https://github.com/Djluz/we_learn' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black'>View Github</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className='flex-1 transition ease-in-out delay-150 rounded-lg shadow-lg group basis-1/3 hover:shadow-teal-400 hover:cursor-pointer'>
              <div className='relative overflow-hidden rounded-lg'>
                <Image src={web5} className='object-cover rounded-lg' width={'100%'} height={'100%'} layout='responsive' />
                <div className='absolute flex flex-col items-center justify-center w-full h-full transition-all duration-300 rounded-lg opacity-0 bg-black/70 -bottom-10 group-hover:bottom-0 group-hover:opacity-100'>
                  <p className='px-5 py-5 text-sm text-black bg-white bg-opacity-90 md:text-xl'>Math-Game is a mathematical game application/website for kids to play while learning or mastering basic arithmetics. This project is created using ReactJS.</p>
                  <div className='flex justify-center gap-2 mt-5 text-sm md:gap-10 md:text-lg lg:gap-3 xl:gap-10'>
                    <a href='https://math-game-z.djluz.website/' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black' >View Website</button>
                    </a>
                    <a href='https://github.com/Djluz/math-game' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black'>View Github</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className='flex-1 transition ease-in-out delay-150 rounded-lg shadow-lg group basis-1/3 hover:shadow-teal-400 hover:cursor-pointer'>
              <div className='relative overflow-hidden rounded-lg'>
                <Image src={web6} className='object-cover rounded-lg' width={'100%'} height={'100%'} layout='responsive' />
                <div className='absolute flex flex-col items-center justify-center w-full h-full transition-all duration-300 rounded-lg opacity-0 bg-black/70 -bottom-10 group-hover:bottom-0 group-hover:opacity-100'>
                  <p className='px-5 py-5 text-sm text-black bg-white bg-opacity-90 md:text-xl'>DJ Luz is a Portfolio website I created for personal use to showcase my projects in web developing. I created this project using NextJS and Tailwindcss. </p>
                  <div className='flex justify-center gap-2 mt-5 text-sm md:gap-10 md:text-lg lg:gap-3 xl:gap-10'>
                    <a href='https://djluz.website/' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black' >View Website</button>
                    </a>
                    <a href='https://github.com/Djluz/myportfolio' target='_blank'>
                      <button className='px-5 py-2 text-white rounded-lg shadow-lg bg-gradient-to-r from-cyan-500 to-teal-500 hover:shadow-gray-500 hover:text-black'>View Github</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

{/*-------------- fifth page------------- */}
<section className='pt-[50px] text-center mx-auto' id="contact">
          <div>

            <Contact />

          </div>
        </section>


      </main>
    </div>
  )
}

